# fly.toml app configuration file generated for bold-morning-4490 on 2024-08-09T06:13:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bold-morning-4490'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
